name: mars
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - aiohttp=3.8.3=py38h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py38haa95532_0
  - attrs=22.1.0=py38haa95532_0
  - blas=1.0=mkl
  - blinker=1.4=py38haa95532_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2023.01.10=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py38haa95532_0
  - cffi=1.15.1=py38h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - contourpy=1.0.5=py38h59b6b97_0
  - cryptography=39.0.1=py38h21b164f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - flatbuffers=2.0.0=h6c2663c_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py38h2bbff1b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py38hc60d5dd_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h5py=3.7.0=py38h3de5c98_0
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py38haa95532_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - keras=2.10.0=py38haa95532_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcurl=7.87.0=h86230a5_0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.5.0=h6c2663c_2
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py38haa95532_0
  - markupsafe=2.1.1=py38h2bbff1b_0
  - matplotlib=3.7.0=py38haa95532_0
  - matplotlib-base=3.7.0=py38hf11a4ad_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - multidict=6.0.2=py38h2bbff1b_0
  - munkres=1.1.4=py_0
  - numpy-base=1.23.5=py38h4da318b_0
  - oauthlib=3.2.1=py38haa95532_0
  - openssl=1.1.1t=h2bbff1b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py38haa95532_0
  - pcre=8.45=hd77b12b_0
  - pillow=9.4.0=py38hd77b12b_0
  - ply=3.11=py38_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38haa95532_0
  - pyopenssl=23.0.0=py38haa95532_0
  - pyparsing=3.0.9=py38haa95532_0
  - pyqt=5.15.7=py38hd77b12b_0
  - pyqt5-sip=12.11.0=py38hd77b12b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.16=h6244533_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h3ad3cdb_4
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.10.0=py38h321e85e_1
  - setuptools=65.6.3=py38haa95532_0
  - sip=6.6.2=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h6c2663c_0
  - sqlite=3.40.1=h2bbff1b_0
  - tensorboard=2.10.0=py38haa95532_0
  - tensorboard-data-server=0.6.1=py38haa95532_0
  - tensorboard-plugin-wit=1.8.1=py38haa95532_0
  - tensorflow=2.10.0=mkl_py38ha5c4042_0
  - tensorflow-base=2.10.0=mkl_py38h6a7f48e_0
  - tensorflow-estimator=2.10.0=py38haa95532_0
  - termcolor=2.1.0=py38haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py38h2bbff1b_0
  - tqdm=4.64.1=py38haa95532_0
  - urllib3=1.26.14=py38haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - werkzeug=2.2.2=py38haa95532_0
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - wrapt=1.14.1=py38h2bbff1b_0
  - xz=5.2.10=h8cc25b3_1
  - yarl=1.8.1=py38h2bbff1b_0
  - zipp=3.11.0=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.5.2
    - clarabel==0.9.0
    - cloudpickle==2.2.1
    - cvxpy==1.5.2
    - cython==0.29.33
    - deepseek-vl==0.0.1.dev0
    - distro==1.9.0
    - dm-control==1.0.15
    - dm-env==1.6
    - dm-tree==0.1.8
    - dtw==1.4.0
    - easy-tf-log==1.12
    - ecos==2.0.14
    - et-xmlfile==2.0.0
    - etils==1.3.0
    - exceptiongroup==1.2.2
    - farama-notifications==0.0.4
    - fastdtw==0.3.4
    - fasteners==0.18
    - filelock==3.16.1
    - fsspec==2024.6.0
    - glfw==2.5.6
    - gradio-client==1.3.0
    - gym==0.25.0
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.29.1
    - hydra-core==1.3.2
    - imageio==2.32.0
    - importlib-metadata==6.0.0
    - jieba==0.42.1
    - jinja2==3.1.2
    - jiter==0.9.1
    - joblib==1.4.2
    - labmaze==1.0.6
    - lazy-loader==0.3
    - libclang==13.0.0
    - lockfile==0.12.2
    - lxml==4.9.3
    - metaworld==2.0.0
    - mpmath==1.3.0
    - mujoco==2.3.7
    - mujoco-py==2.1.2.14
    - networkx==3.1
    - numpy==1.24.4
    - omegaconf==2.3.0
    - openai==0.28.0
    - opencv-python==4.10.0.84
    - openpyxl==3.1.5
    - osqp==0.6.7.post3
    - pandas==2.0.3
    - pip==23.3.1
    - protobuf==3.19.0
    - psutil==6.0.0
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygame==2.6.1
    - pyopengl==3.1.6
    - pyproject==1.3.1
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - qdldl==0.1.7.post5
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.2
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scs==3.2.7.post2
    - seaborn==0.13.0
    - sniffio==1.3.1
    - some-package==0.1
    - sympy==1.13.3
    - tensorflow-io-gcs-filesystem==0.23.1
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tokenizers==0.20.3
    - torch==1.8.0
    - torch-geometric==2.5.3
    - transformers==4.46.3
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - websockets==12.0
prefix: C:\Anaconda3\envs\mars
